### ISSUE TITLE
Broken links in media mentions

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-wiki#300]
As seen in http://wiki.aragon.one/press/media-mentions/

**Comment by antonyip** [comment]
Hi, I'm assuming that the issue is here?

![image](https://user-images.githubusercontent.com/9086733/54806411-ddc4d780-4cb4-11e9-8a53-4cbdf7315600.png)

If so, I would like to revert commit https://github.com/aragon/aragon-wiki/commit/30536d822bcf66ec63eff6506582820a74da1104 as it seems like changing the http to https was a mistake.

The Reuters's logo doesn't have the http changed to https and appears to be working.. thus my conclusion of that commit causing the issue.
