### ISSUE TITLE
Remove requirement of healthy Github / open source profiles in jobs

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-wiki#313]
It's been brought up a few times, but requiring healthy open source profiles can exclude a large number of people who would otherwise apply. Especially true for certain roles, like the DevOps position.

Could we make the requirement gentler, e.g. as an added bonus, etc? Or at least take it out of the roles where it's less common?

**Comment by john-light** [comment]
In general this "very active and healthy GitHub profile" requirement is excluding talented devs who have been in BigCo environments or just working on personal projects where they are committing to private repos more often than not. There was a lot of discussion on Twitter about this fairly recently e.g. https://twitter.com/dcousineau/status/1004850735622819840 and https://twitter.com/alicegoldfuss/status/1004843499580055553

**Comment by luisivan** [comment]
I think for certain roles this is a must, since it tells a lot about the culture of the candidate. It also tells about the hard skills, but I do agree that a candidate might have the hard skills without necessarily showcasing them on GitHub. But for devops for example, it's true that it is not as relevant

**Comment by john-light** [comment]
Job listings were moved out of the wiki in https://github.com/aragon/aragon-wiki/pull/447
